const Login = require("../models/Login");
const UserAccessToken = require('../models/UserAccessTokens')
var randomize = require('randomatic');
var TokenGenerator = require('token-generator')({
  salt: 'your secret ingredient for this magic recipe',
  timestampMap: 'abcdefghij', // 10 chars array for obfuscation proposes
});

exports.handleUserAuth = (req, res) => {

  console.log("SIGN IN ATTEMPT FROM :", req.body)
  Login.findOne({ username: req.body.username }, (err, account) => {
    if (err) {
      console.log("Error in Server ", account)
      res.status(500).send({ 'status': 'failure', 'err': 'No account found against this username!' });
    }
    if (account != null || account != undefined) {
      console.log("Account found", account)
      res.status(200).json({ 'status': 'success', 'data': account });
    }
    else {
      console.log("Account not found")
      if (req.body.username == 'admin') {
        //Create AutoGenerated Password
        let password = randomize('0', 6)
        let userData = { password }
        console.log('here is autogenerated password', userData)
        //save in db
        let newAccount = new Login(userData)
        newAccount.save((err, account) => {
          if (err) {
            console.log("failure in creating account", err);
            res.status(500).json({ 'status': 'failure', 'err': err });
          }
          else {
            console.log("account created", account);
            res.status(200).json({ 'status': 'success', 'data': account });
          }
        });
      } else {
        res.status(500).json({ 'status': 'failure', 'err': 'No account found against this username!' });
      }


    }
  });


}

exports.handlePassAuth = (req, res) => {

  console.log("SIGN IN ATTEMPT FROM :", req.body)
  Login.findOne({ username: req.body.username, password: req.body.password }, (err, account) => {
    if (err) {
      console.log("Error in Server ", account)
      res.status(500).send({ 'status': 'failure', 'err': 'Enter correct Pin code' });
    }
    if (account != null || account != undefined) {
      console.log("Account found", account)
      //For AccessToken
      var token = TokenGenerator.generate();
      var accessToken = {
        token: token,
        userAccount: account._id,

      }

      var newtoken = new UserAccessToken(accessToken)
      newtoken.save((err, tokendata) => {
        if (err) {
          res.status(500).json({ 'status': 'failure', 'err': err, 'email': req.body.email });
        } else {
          var tokenObject = { 'token': token, 'userId': account._id }
          res.status(200).json({ 'status': 'success', 'token': tokenObject })
        }
      })


    }
    else {
      console.log("Account not found")
      res.status(500).json({ 'status': 'failure', 'err': 'Enter correct Pin code!' });

    }
  });


}

