export const device_Actions = {
    device_List: {
        NEW: "DEVICE_NEW",
        POST: "DEVICE_POST",
        SUCCESS: "DEVICE_SUCCESS",
        FAILURE: "DEVICE_FAILURE",
        NETWORK_FAILURE: "DEVICE_NETWORK_FAILUIRE",
        ADD_SUCCESS:'DEVICE_ADD_SUCCESS',
        EDIT_SUCCESS:'DEVICE_EDIT_SUCCESS',
        DELETE_SUCCESS:'DEVICE_DELETE_SUCCESS',
    }
}


export const device_Status = {
    device_List: {
        NEW: "DEVICE_NEW",
        LOADING: "DEVICE_POST",
        SUCCESS: "DEVICE_SUCCESS",
        FAILURE: "DEVICE_FAILURE",
        NETWORK_FAILURE: "DEVICE_NETWORK_FAILUIRE",
        ADD_SUCCESS:'DEVICE_ADD_SUCCESS',
        EDIT_SUCCESS:'DEVICE_EDIT_SUCCESS',
        DELETE_SUCCESS:'DEVICE_DELETE_SUCCESS',
    }
}
