export const login_Actions= {
	login_SignIn :{
    NEW:"LOGIN_ACCOUNT_NEW",
    POST:"LOGIN_ACCOUNT_POST",
		AUTHORIZED: "LOGIN_ACCOUNT_AURHORIZED",
		NOT_AUTHORIZED: "LOGIN_ACCOUNT_NOT_AUTHORIZED",
		USER_AUTH_FAILURE: "USER_AUTH_FAILURE",
		PASS_AUTH_FAILURE: "PASS_AUTH_FAILURE",
		LOGINPASSWORD:"LOGIN_PASSWORD",
		NETWORK_FAILURE:"LOGIN_NETWORK_FAILUIRE"
	}
}


export const login_Status ={
	login_SignIn :{
    NEW:"LOGIN_ACCOUNT_NEW",
    AUTHORIZED: "LOGIN_ACCOUNT_AURHORIZED",
		NOT_AUTHORIZED: "LOGIN_ACCOUNT_NOT_AUTHORIZED",
		USER_AUTH_FAILURE: "USER_AUTH_FAILURE",
		PASS_AUTH_FAILURE: "PASS_AUTH_FAILURE",
		LOADING:"LOGIN_ACCOUNT_LOADING",
		LOGINPASSWORD:"LOGIN_PASSWORD",
		NETWORK_FAILURE:"LOGIN_NETWORK_FAILUIRE"
	}


}
